CC=gcc
FLAGS=-Wall -Werror -g

tdidf:
	$(CC) $(FLAGS) -lm *.c -o searchTfIdf
	./searchTfIdf mars
	./searchTfIdf Mars has long been the subject of human interest Early telescopic observations revealed color changes on the surface that were attributed to seasonal vegetation and apparent linear features were ascribed to intelligent design
clean:
	rm -f *.exe
	rm -f searchTfIdf
